### ISSUE TITLE
Failed summarise vcf step due to the header of the consensus

### ISSUE THREAD

**Issue by kusonahikari** [m-crown/SPEAR#27]
I run `spear consensus . --threads 16 spear_output` with the latest version of spear. The speed is much faster but failed `summarise_vcf` step with following message 

> shell:

> 
        for i in $(grep -lP '^NC_045512\.2' spear_output/final_vcfs/*.spear.vcf); do BNAME=${i##*/}; BNAME2=${BNAME%.spear.vcf}; grep -v '^#' $i | grep -v '^#' $i | sed "s|^NC_045512\.2|$BNAME2|g"; done > spear_output/intermediate_output/anno_concat.tsv ; convert_format.py --is_vcf_input False --is_filtered False spear_output/intermediate_output/anno_concat.tsv spear_output /home/ubuntu/miniconda3/envs/spear/data spear_output/all_samples.spear.vcf YenBai_908_Delta_2021_08_01 YenBai_604_Delta_2021_04_22 YenBai_1821_Delta_2021_12_28 YenBai_605_Delta_2021_04_24 YenBai_1451_Delta_2021_04_27 YenBai_516_Delta_2021_05_05 2> spear_output/intermediate_output/logs/summarise/summary.log

I changed my fasta header from `YenBai_605/Delta/2021-04-24` to `YenBai_605_Delta_2021_04_24` and didn't have this error anymore.

**Comment by m-crown** [comment]
#256c394 should solve this. It was an missing set of double braces around a bash variable. Let me know if you still get this error, and if you do could you share an example file and the command you ran.

**Comment by kusonahikari** [comment]
Thanks alot. After I update `spear`, everything ran smoothly.  I also noted that there is a limit threshold of how many consensus to put into `spear`. Had to split >1000 seqs into two batches.

**Comment by m-crown** [comment]
Great that it is working for you now. Could you elaborate on the error you are encountering with input files ? I routinely run upwards of 5000 samples now and do not have any errors. It may be of interest to you to see this part of the readme : Note that running on multiple input files may require you to increase the maximum number of open file handles on your system if your number of input samples starts to approach this limit, check this with ulimit -n.

Hope this helps
