### ISSUE TITLE
Error when trying to use my vcf as input

### ISSUE THREAD

**Issue by AndreaAguadoM** [m-crown/SPEAR#34]
Hello, I am having problems when trying to use spear to analyze my vcf sample. When I execute the following line: 

spear vcf inputs sample_output

I get the following error: 
----------------------------------------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/aaguado/miniconda3/envs/spear/bin/summarise_snpeff.py", line 261, in <module>
    main()
  File "/home/aaguado/miniconda3/envs/spear/bin/summarise_snpeff.py", line 214, in main
    cols.insert(cols.index("AC") + 1, "problem_exc")
ValueError: 'AC' is not in list
[Thu Sep  8 12:52:47 2022]
Error in rule spear_annotate:
    jobid: 2
    output: spear_output/final_vcfs/AND19730.spear.vcf
    log: spear_output/intermediate_output/logs/spear/AND19730.log (check log file(s) for error message)
    shell:
        summarise_snpeff.py spear_output/final_vcfs/AND19730.spear.vcf spear_output/intermediate_output/snpeff/AND19730.ann.vcf /home/aaguado/miniconda3/envs/spear/data ; spear_annotate.py spear_output/final_vcfs/AND19730.spear.vcf spear_output/final_vcfs/AND19730.spear.vcf /home/aaguado/miniconda3/envs/spear/data 2> spear_output/intermediate_output/logs/spear/AND19730.log
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Exiting because a job execution failed. Look above for error message

------------------------------------------------------------------------------------------------------------------------

I do not know which the error is. If someone could help me I would really appreciate it!

**Comment by AndreaAguadoM** [comment]
My vcf file was generated via iVar, I do not know if the employed tool could be related to this issue

**Comment by m-crown** [comment]
Hi , please attach an example VCF file if possible and I will look into this.

**Comment by m-crown** [comment]
Closing as have responded in #35
