### ISSUE TITLE
Dependency errors when trying to install software

### ISSUE THREAD

**Issue by AngelSevillarobles** [m-crown/SPEAR#42]
**Describe the bug**
When trying to run the ./install_spear script, dependency errors make impossible to create the environment.
I've tried in different environments including a clean AlmaLinux release 9.1 minimal installation.
UnsatisfiableError: The following specifications were found to be incompatible with each other

I've tried creating the environment manually with mamba and the result is:
Could not solve for environment specs
The following package could not be installed
└─ grep   is uninstallable because it conflicts with any installable versions previously reported.

**To Reproduce**
1.Execute ./install_spear
2.Package ''X'' conflicts for:

**Desktop (please complete the following information):**
 - OS: AlmaLinux release 9.1 minimal installation. Rocky Linux 8

**Comment by m-crown** [comment]
Hi, I think I have fixed this with release 1.1.3. It was an issue with a bioconda package. I have changed the channel spec for it. Please can you try pulling the latest version and installing this.

**Comment by AngelSevillarobles** [comment]
Solved, thank you very much for your quick work!
