### ISSUE TITLE
v1.1.3: bcftools merge needs --force-single for single sequences

### ISSUE THREAD

**Issue by lukebsnell** [m-crown/SPEAR#45]
Error in rule merge_vcfs:
    jobid: 6
    output: output/intermediate_output/merged.vcf
    log: output/intermediate_output/logs/merge/merge.log (check log file(s) for error message)
    shell:
        find output/intermediate_output/indels/ -type f -name "*.indels.vcf" > output/intermediate_output/merge_list.txt ; bcftools merge --no-index -m none -o output/intermediate_output/merged.vcf -l output/intermediate_output/merge_list.txt 2> output/intermediate_output/logs/merge/merge.log
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Exiting because a job execution failed. Look above for error message

Fixed by adding --force-single to bcftools merge command in conda env spear/bin/pipeline.smk, line 165

**Comment by m-crown** [comment]
Hi Luke, I am looking into this, could you provide a sample file which produces the error you describe that is fixed by adding the --force-single param?

**Comment by m-crown** [comment]
Hi @lukebsnell , I have added this fix to the latest v2.0.0 release. This release includes a number of changes, when running from the new version please be sure to fully reinstall SPEAR!

**Comment by lukebsnell** [comment]
thank you.

**Comment by m-crown** [comment]
@lukebsnell , I am interested in learning more about your use case for SPEAR - if you would be willing to share could you reach out to me @ matthew.crown [at] northumbria.ac.uk ?
